# pandas

In [1]:
import pandas as pd

In [6]:
# DataFram: build from a dictionary

In [7]:
data={"name":["a","b","c"],"marks":[90,89,74],"city":["hr","dl","pb"]}

In [8]:
df=pd.DataFrame(data)

In [9]:
print(df)

  name  marks city
0    a     90   hr
1    b     89   dl
2    c     74   pb

In [14]:
data={"name":["a","b","c","d","e","f","g"],
      "marks":[90,89,74,89,89,90,67],
      "city":["hr","dl","pb","raj","ap","kl","hp"],
      "fathers name":["bb","cc","dd","ee","ff","gg","hh"]}

In [16]:
df=pd.DataFrame(data)

In [17]:
print(df)

  name  marks city fathers name
0    a     90   hr           bb
1    b     89   dl           cc
2    c     74   pb           dd
3    d     89  raj           ee
4    e     89   ap           ff
5    f     90   kl           gg
6    g     67   hp           hh

In [20]:
df.shape

(7, 4)

In [24]:
df.head(3)

  name  marks city fathers name
0    a     90   hr           bb
1    b     89   dl           cc
2    c     74   pb           dd

In [25]:
df.tail(3)

  name  marks city fathers name
4    e     89   ap           ff
5    f     90   kl           gg
6    g     67   hp           hh

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          7 non-null      str
 1   marks         7 non-null      int64
 2   city          7 non-null      str
 3   fathers name  7 non-null      str
dtypes: int64(1), str(3)
memory usage: 356.0 bytes

In [28]:
df.describe()

           marks
count   7.000000
mean   84.000000
std     9.451631
min    67.000000
25%    81.500000
50%    89.000000
75%    89.500000
max    90.000000

In [10]:
import pandas as pd
df=pd.read_csv("st.csv")
print(df)
print(df.dropna())
print(df.isna().sum())
print(df.fillna(0))
# print(df.fillna(df['English'].mean()))


df.to_excel("hel.xlsx")

print(df)

   Student_ID Student_Name English   Maths  Science
0         101        Rahul      78      88       82
1         102        Priya      85      91       79
2         103         Aman  ninety      76       88
3         104         Neha      67     NaN       65
4         105        Rohit     NaN      95      101
5         106       Simran      92  eighty       90
6         107        Vikas     105      89      NaN
7         108       Anjali      74      72       77
8         108       Anjali      74      72       77
9         110          NaN      81      84  seventy
   Student_ID Student_Name English   Maths Science
0         101        Rahul      78      88      82
1         102        Priya      85      91      79
2         103         Aman  ninety      76      88
5         106       Simran      92  eighty      90
7         108       Anjali      74      72      77
8         108       Anjali      74      72      77
Student_ID      0
Student_Name    1
English         1
Maths           1
Science         1
dtype: int64
   Student_ID Student_Name English   Maths  Science
0         101        Rahul      78      88       82
1         102        Priya      85      91       79
2         103         Aman  ninety      76       88
3         104         Neha      67       0       65
4         105        Rohit       0      95      101
5         106       Simran      92  eighty       90
6         107        Vikas     105      89        0
7         108       Anjali      74      72       77
8         108       Anjali      74      72       77
9         110            0      81      84  seventy
   Student_ID Student_Name English   Maths  Science
0         101        Rahul      78      88       82
1         102        Priya      85      91       79
2         103         Aman  ninety      76       88
3         104         Neha      67     NaN       65
4         105        Rohit     NaN      95      101
5         106       Simran      92  eighty       90
6         107        Vikas     105      89      NaN
7         108       Anjali      74      72       77
8         108       Anjali      74      72       77
9         110          NaN      81      84  seventy

In [12]:
import pandas as pd
df=pd.read_excel("hel.xlsx")
df.to_csv("st11.csv",index =False)
print(df)

   Unnamed: 0  Student_ID Student_Name English   Maths  Science
0           0         101        Rahul      78      88       82
1           1         102        Priya      85      91       79
2           2         103         Aman  ninety      76       88
3           3         104         Neha      67     NaN       65
4           4         105        Rohit     NaN      95      101
5           5         106       Simran      92  eighty       90
6           6         107        Vikas     105      89      NaN
7           7         108       Anjali      74      72       77
8           8         108       Anjali      74      72       77
9           9         110          NaN      81      84  seventy